"""Alert cut-points and plausibility bounds.

GENERATED FILE — DO NOT EDIT.
Source: packages/tokens/tokens.json  (spec: docs/design.md §3)
Regenerate: node packages/tokens/generate.mjs

These are shared with the Flutter client, which evaluates alerts locally so
an SpO2 of 88% raises an emergency without a network. Two hand-maintained
copies would drift, and "is this dangerous" would have two answers.
"""

# ── alert cut-points ──
SPO2_WARNING = 95.0
SPO2_CRITICAL = 90.0
HEART_RATE_NORMAL_MIN = 60.0
HEART_RATE_NORMAL_MAX = 100.0
HEART_RATE_LOW_WARNING = 50.0
HEART_RATE_LOW_CRITICAL = 40.0
HEART_RATE_HIGH_WARNING = 120.0
HEART_RATE_HIGH_CRITICAL = 150.0
TEMPERATURE_NORMAL_MIN = 36.1
TEMPERATURE_NORMAL_MAX = 37.2
TEMPERATURE_FEVER_WARNING = 37.5
TEMPERATURE_FEVER_CRITICAL = 39.0
TEMPERATURE_HYPOTHERMIA_CRITICAL = 35.0
BLOOD_PRESSURE_STAGE1_SYSTOLIC = 130.0
BLOOD_PRESSURE_STAGE1_DIASTOLIC = 80.0
BLOOD_PRESSURE_STAGE2_SYSTOLIC = 140.0
BLOOD_PRESSURE_STAGE2_DIASTOLIC = 90.0
BLOOD_PRESSURE_CRISIS_SYSTOLIC = 180.0
BLOOD_PRESSURE_CRISIS_DIASTOLIC = 120.0

# ── plausibility bounds ──
PLAUSIBLE_SYSTOLIC_MIN = 50.0
PLAUSIBLE_SYSTOLIC_MAX = 300.0
PLAUSIBLE_DIASTOLIC_MIN = 25.0
PLAUSIBLE_DIASTOLIC_MAX = 200.0
PLAUSIBLE_HEART_RATE_MIN = 25.0
PLAUSIBLE_HEART_RATE_MAX = 250.0
PLAUSIBLE_SPO2_MIN = 50.0
PLAUSIBLE_SPO2_MAX = 100.0
PLAUSIBLE_TEMPERATURE_MIN = 30.0
PLAUSIBLE_TEMPERATURE_MAX = 45.0
PLAUSIBLE_AMBIENT_TEMPERATURE_MIN = 0.0
PLAUSIBLE_AMBIENT_TEMPERATURE_MAX = 60.0
